package com.nutomic.syncthingandroid.model

import org.junit.Assert.assertFalse
import org.junit.Assert.assertTrue
import org.junit.Test
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

/**
 * Unit tests for device ID and device address validation.
 * The positive address cases mirror the in-code self-test in
 * [Device.testCheckDeviceAddress].
 */
@RunWith(RobolectricTestRunner::class)
@Config(sdk = [34])
class DeviceTest {

    companion object {
        /** A real-format 56 char device ID (as generated by syncthing core). */
        private const val VALID_DEVICE_ID =
            "LVEIZX7-6P5X5UC-I4CFK5D-E6TRZTH-G5BX3LM-DCNHIEV-YI6S6OU-64Z7JQ2"
    }

    @Test
    fun checkDeviceID_acceptsValidId() {
        val device = Device()
        device.deviceID = VALID_DEVICE_ID
        assertTrue(device.checkDeviceID())
    }

    @Test
    fun checkDeviceID_acceptsIdWithTypoCharsAndSpaces() {
        // 1->I replacement and removed spaces/dashes are part of the algorithm.
        val device = Device()
        device.deviceID = VALID_DEVICE_ID.replaceFirst("I", "1").replace("-", " ")
        assertTrue(device.checkDeviceID())
    }

    @Test
    fun checkDeviceID_rejectsEmptyId() {
        val device = Device()
        device.deviceID = ""
        assertFalse(device.checkDeviceID())
    }

    @Test
    fun checkDeviceID_rejectsWrongLength() {
        val device = Device()
        device.deviceID = "LVEIZX7-6P5X5UC"
        assertFalse(device.checkDeviceID())
    }

    @Test
    fun checkDeviceID_rejectsIncorrectCheckDigit() {
        // Corrupt the last character: breaks the luhn check digit of the last group.
        val device = Device()
        device.deviceID = VALID_DEVICE_ID.substring(0, VALID_DEVICE_ID.length - 1) + "A"
        if (device.deviceID == VALID_DEVICE_ID) {
            return // skip if substitution did not change anything
        }
        assertFalse(device.checkDeviceID())
    }

    @Test
    fun checkDeviceAddresses_acceptsValidAddresses() {
        val device = Device()
        device.addresses = arrayListOf(
            "tcp://127.0.0.1:4000",
            "tcp4://127.0.0.1:4000",
            "tcp6://127.0.0.1:4000",
            "tcp4://127.0.0.1",
            "tcp://[2001:db8::23:42]",
            "tcp://[2001:db8::23:42]:12345",
            "tcp://myserver",
            "tcp://myserver:12345",
            "relay://stlocal:22067/?id=ID-REDACTED&pingInterval=30s&networkTimeout=2m0s" +
                "&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=REDACTED",
            "relay://stlocal:22067",
            "quic://127.0.0.1",
            "quic://127.0.0.1:24000",
            "quic4://127.0.0.1:24000",
            "quic6://127.0.0.1:24000",
            "dynamic"
        )
        assertTrue(device.checkDeviceAddresses())
    }

    @Test
    fun checkDeviceAddresses_rejectsInvalidAddresses() {
        for (invalid in arrayOf(
            "tcp://myserver:",
            "tcp8://127.0.0.1",
            "udp4://127.0.0.1",
            "tcp://:4000",
            "tcp://tcp://myserver:4000"
        )) {
            val device = Device()
            device.addresses = arrayListOf(invalid)
            assertFalse("Expected \"$invalid\" to be rejected", device.checkDeviceAddresses())
        }
    }

    @Test
    fun checkDeviceAddresses_rejectsNullAddresses() {
        val device = Device()
        device.addresses = null
        assertFalse(device.checkDeviceAddresses())
    }
}
